# -*- encoding: utf-8 -*-

=begin
#CyberSource Flex API

#Simple PAN tokenization service

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "cybersource_rest_client/version"

Gem::Specification.new do |s|
  s.name        = "cybersource_rest_client"
  s.version     = "0.0.85"
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["CyberSource"]
  s.email       = ["cybersourcedev@gmail.com"]
  s.homepage    = "https://developer.cybersource.com"
  s.summary     = "CyberSource Ruby SDK Gem"
  s.description = "Simple REST API for the CyberSource Global Payments Platform"
  s.license     = "CyberSource"
  s.files       = Dir.glob("{lib}/{cybersource_rest_client}/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/authentication/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/core/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/util/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/logging/**/*") + Dir.glob("{lib}/cybersource_rest_client.rb")
  s.required_ruby_version = ">= 3.1"

  s.add_runtime_dependency 'typhoeus', '~> 1.5','>=1.5.0'
  s.add_runtime_dependency 'json', '~>2.18', '>= 2.18.1'
  # Tripleseat fork: upstream pins '~> 7.2' (<8.0), unresolvable against this app's activesupport 8.1.2 (Rails 8).
  # See https://github.com/CyberSource/cybersource-rest-client-ruby/issues/121 (open, unmerged PR #125).
  s.add_runtime_dependency 'activesupport', '>= 7.2.3.1'
  s.add_runtime_dependency 'interface','~> 1.0', '>= 1.0.5'
  # Tripleseat fork IOU, tied to TPD-12071: loosened from upstream's '~> 3.1' so this app's
  # omniauth-facebook -> oauth2 -> jwt (< 3.0) chain still resolves. This is a temporary shim, not
  # a fix - jwt 3.x requires signature verification before payload access, which breaks the
  # unverified JWT.decode calls in cybersource_account.rb. Remove this override once TPD-12071
  # (HTTP Signature -> JWT+MLE migration) fixes those call sites and the omniauth-facebook chain.
  s.add_runtime_dependency 'jwt', '>= 2.10', '< 4'
  s.add_runtime_dependency 'addressable', '~> 2.8', '>= 2.8.8'
  s.add_runtime_dependency 'time', '~>0.4.2'
  s.add_runtime_dependency 'jose', '~> 1.2'

  s.add_development_dependency 'rubocop', '>=1.31.0','<1.31.1'
  s.add_development_dependency 'rspec', '~> 3.13', '>= 3.13.2'
  s.add_development_dependency 'vcr', '~> 6.4.0'
  s.add_development_dependency 'autotest', '~> 5.0', '>= 5.0.0'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.3.1', '>= 0.3.1'
  
  s.require_paths = ["lib"]
end
