=begin
#CyberSource Merged Spec

#All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.38
=end

require 'date'

module CyberSource
  class PushFunds201ResponseIssuerInformation
    # Domestic indicator for Push funds (OCT). If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_domestic_participant_indicator

    # Cross-border indicator for push funds (OCT). If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_cross_border_participant_indicator

    # Indicates whether domestic money transfer OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.        Supported for Visa Direct. 
    attr_accessor :oct_money_transfer_domestic_indicator

    # Indicates whether cross-border money transfer OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_money_transfer_cross_border_indicator

    # Indicates whether domestic money transfer OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_money_transfer_fast_funds_domestic_indicator

    # Indicates whether cross-border money transfer OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_money_transfer_fast_funds_cross_border_indicator

    # This field indicates if the recipient issuer can accept push funds (OCT) transactions from the merchant country.  If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_money_transfer_merchant_country_restricted

    # Indicates whether domestic non-money transfer OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_non_money_transfer_domestic_indicator

    # Indicates whether cross-border non-money transfer OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_non_money_transfer_cross_border_indicator

    # Indicates whether domestic non-money transfer OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_non_money_transfer_fast_funds_domestic_indicator

    # Indicates whether cross-border non-money transfer OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_non_money_transfer_fast_funds_cross_border_indicator

    # Indicates whether domestic gambling OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_online_gambling_domestic_indicator

    # Indicates whether cross-border gambling OCTs (push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_online_gambling_cross_border_indicator

    # Indicates whether domestic gambling OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_online_gambling_fast_funds_domestic_indicator

    # Indicates whether cross-border gambling OCTs (fast push funds) are allowed. If no Funds Transfer Attributes Inquiry data is available for this card account, the field is omitted.   Supported for Visa Direct. 
    attr_accessor :oct_online_gambling_fast_funds_cross_border_indicator

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'oct_domestic_participant_indicator' => :'octDomesticParticipantIndicator',
        :'oct_cross_border_participant_indicator' => :'octCrossBorderParticipantIndicator',
        :'oct_money_transfer_domestic_indicator' => :'octMoneyTransferDomesticIndicator',
        :'oct_money_transfer_cross_border_indicator' => :'octMoneyTransferCrossBorderIndicator',
        :'oct_money_transfer_fast_funds_domestic_indicator' => :'octMoneyTransferFastFundsDomesticIndicator',
        :'oct_money_transfer_fast_funds_cross_border_indicator' => :'octMoneyTransferFastFundsCrossBorderIndicator',
        :'oct_money_transfer_merchant_country_restricted' => :'octMoneyTransferMerchantCountryRestricted',
        :'oct_non_money_transfer_domestic_indicator' => :'octNonMoneyTransferDomesticIndicator',
        :'oct_non_money_transfer_cross_border_indicator' => :'octNonMoneyTransferCrossBorderIndicator',
        :'oct_non_money_transfer_fast_funds_domestic_indicator' => :'octNonMoneyTransferFastFundsDomesticIndicator',
        :'oct_non_money_transfer_fast_funds_cross_border_indicator' => :'octNonMoneyTransferFastFundsCrossBorderIndicator',
        :'oct_online_gambling_domestic_indicator' => :'octOnlineGamblingDomesticIndicator',
        :'oct_online_gambling_cross_border_indicator' => :'octOnlineGamblingCrossBorderIndicator',
        :'oct_online_gambling_fast_funds_domestic_indicator' => :'octOnlineGamblingFastFundsDomesticIndicator',
        :'oct_online_gambling_fast_funds_cross_border_indicator' => :'octOnlineGamblingFastFundsCrossBorderIndicator'
      }
    end

    # Attribute mapping from JSON key to ruby-style variable name.
    def self.json_map
      {
        :'oct_domestic_participant_indicator' => :'oct_domestic_participant_indicator',
        :'oct_cross_border_participant_indicator' => :'oct_cross_border_participant_indicator',
        :'oct_money_transfer_domestic_indicator' => :'oct_money_transfer_domestic_indicator',
        :'oct_money_transfer_cross_border_indicator' => :'oct_money_transfer_cross_border_indicator',
        :'oct_money_transfer_fast_funds_domestic_indicator' => :'oct_money_transfer_fast_funds_domestic_indicator',
        :'oct_money_transfer_fast_funds_cross_border_indicator' => :'oct_money_transfer_fast_funds_cross_border_indicator',
        :'oct_money_transfer_merchant_country_restricted' => :'oct_money_transfer_merchant_country_restricted',
        :'oct_non_money_transfer_domestic_indicator' => :'oct_non_money_transfer_domestic_indicator',
        :'oct_non_money_transfer_cross_border_indicator' => :'oct_non_money_transfer_cross_border_indicator',
        :'oct_non_money_transfer_fast_funds_domestic_indicator' => :'oct_non_money_transfer_fast_funds_domestic_indicator',
        :'oct_non_money_transfer_fast_funds_cross_border_indicator' => :'oct_non_money_transfer_fast_funds_cross_border_indicator',
        :'oct_online_gambling_domestic_indicator' => :'oct_online_gambling_domestic_indicator',
        :'oct_online_gambling_cross_border_indicator' => :'oct_online_gambling_cross_border_indicator',
        :'oct_online_gambling_fast_funds_domestic_indicator' => :'oct_online_gambling_fast_funds_domestic_indicator',
        :'oct_online_gambling_fast_funds_cross_border_indicator' => :'oct_online_gambling_fast_funds_cross_border_indicator'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'oct_domestic_participant_indicator' => :'BOOLEAN',
        :'oct_cross_border_participant_indicator' => :'BOOLEAN',
        :'oct_money_transfer_domestic_indicator' => :'BOOLEAN',
        :'oct_money_transfer_cross_border_indicator' => :'BOOLEAN',
        :'oct_money_transfer_fast_funds_domestic_indicator' => :'BOOLEAN',
        :'oct_money_transfer_fast_funds_cross_border_indicator' => :'BOOLEAN',
        :'oct_money_transfer_merchant_country_restricted' => :'BOOLEAN',
        :'oct_non_money_transfer_domestic_indicator' => :'BOOLEAN',
        :'oct_non_money_transfer_cross_border_indicator' => :'BOOLEAN',
        :'oct_non_money_transfer_fast_funds_domestic_indicator' => :'BOOLEAN',
        :'oct_non_money_transfer_fast_funds_cross_border_indicator' => :'BOOLEAN',
        :'oct_online_gambling_domestic_indicator' => :'BOOLEAN',
        :'oct_online_gambling_cross_border_indicator' => :'BOOLEAN',
        :'oct_online_gambling_fast_funds_domestic_indicator' => :'BOOLEAN',
        :'oct_online_gambling_fast_funds_cross_border_indicator' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'octDomesticParticipantIndicator')
        self.oct_domestic_participant_indicator = attributes[:'octDomesticParticipantIndicator']
      end

      if attributes.has_key?(:'octCrossBorderParticipantIndicator')
        self.oct_cross_border_participant_indicator = attributes[:'octCrossBorderParticipantIndicator']
      end

      if attributes.has_key?(:'octMoneyTransferDomesticIndicator')
        self.oct_money_transfer_domestic_indicator = attributes[:'octMoneyTransferDomesticIndicator']
      end

      if attributes.has_key?(:'octMoneyTransferCrossBorderIndicator')
        self.oct_money_transfer_cross_border_indicator = attributes[:'octMoneyTransferCrossBorderIndicator']
      end

      if attributes.has_key?(:'octMoneyTransferFastFundsDomesticIndicator')
        self.oct_money_transfer_fast_funds_domestic_indicator = attributes[:'octMoneyTransferFastFundsDomesticIndicator']
      end

      if attributes.has_key?(:'octMoneyTransferFastFundsCrossBorderIndicator')
        self.oct_money_transfer_fast_funds_cross_border_indicator = attributes[:'octMoneyTransferFastFundsCrossBorderIndicator']
      end

      if attributes.has_key?(:'octMoneyTransferMerchantCountryRestricted')
        self.oct_money_transfer_merchant_country_restricted = attributes[:'octMoneyTransferMerchantCountryRestricted']
      end

      if attributes.has_key?(:'octNonMoneyTransferDomesticIndicator')
        self.oct_non_money_transfer_domestic_indicator = attributes[:'octNonMoneyTransferDomesticIndicator']
      end

      if attributes.has_key?(:'octNonMoneyTransferCrossBorderIndicator')
        self.oct_non_money_transfer_cross_border_indicator = attributes[:'octNonMoneyTransferCrossBorderIndicator']
      end

      if attributes.has_key?(:'octNonMoneyTransferFastFundsDomesticIndicator')
        self.oct_non_money_transfer_fast_funds_domestic_indicator = attributes[:'octNonMoneyTransferFastFundsDomesticIndicator']
      end

      if attributes.has_key?(:'octNonMoneyTransferFastFundsCrossBorderIndicator')
        self.oct_non_money_transfer_fast_funds_cross_border_indicator = attributes[:'octNonMoneyTransferFastFundsCrossBorderIndicator']
      end

      if attributes.has_key?(:'octOnlineGamblingDomesticIndicator')
        self.oct_online_gambling_domestic_indicator = attributes[:'octOnlineGamblingDomesticIndicator']
      end

      if attributes.has_key?(:'octOnlineGamblingCrossBorderIndicator')
        self.oct_online_gambling_cross_border_indicator = attributes[:'octOnlineGamblingCrossBorderIndicator']
      end

      if attributes.has_key?(:'octOnlineGamblingFastFundsDomesticIndicator')
        self.oct_online_gambling_fast_funds_domestic_indicator = attributes[:'octOnlineGamblingFastFundsDomesticIndicator']
      end

      if attributes.has_key?(:'octOnlineGamblingFastFundsCrossBorderIndicator')
        self.oct_online_gambling_fast_funds_cross_border_indicator = attributes[:'octOnlineGamblingFastFundsCrossBorderIndicator']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          oct_domestic_participant_indicator == o.oct_domestic_participant_indicator &&
          oct_cross_border_participant_indicator == o.oct_cross_border_participant_indicator &&
          oct_money_transfer_domestic_indicator == o.oct_money_transfer_domestic_indicator &&
          oct_money_transfer_cross_border_indicator == o.oct_money_transfer_cross_border_indicator &&
          oct_money_transfer_fast_funds_domestic_indicator == o.oct_money_transfer_fast_funds_domestic_indicator &&
          oct_money_transfer_fast_funds_cross_border_indicator == o.oct_money_transfer_fast_funds_cross_border_indicator &&
          oct_money_transfer_merchant_country_restricted == o.oct_money_transfer_merchant_country_restricted &&
          oct_non_money_transfer_domestic_indicator == o.oct_non_money_transfer_domestic_indicator &&
          oct_non_money_transfer_cross_border_indicator == o.oct_non_money_transfer_cross_border_indicator &&
          oct_non_money_transfer_fast_funds_domestic_indicator == o.oct_non_money_transfer_fast_funds_domestic_indicator &&
          oct_non_money_transfer_fast_funds_cross_border_indicator == o.oct_non_money_transfer_fast_funds_cross_border_indicator &&
          oct_online_gambling_domestic_indicator == o.oct_online_gambling_domestic_indicator &&
          oct_online_gambling_cross_border_indicator == o.oct_online_gambling_cross_border_indicator &&
          oct_online_gambling_fast_funds_domestic_indicator == o.oct_online_gambling_fast_funds_domestic_indicator &&
          oct_online_gambling_fast_funds_cross_border_indicator == o.oct_online_gambling_fast_funds_cross_border_indicator
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [oct_domestic_participant_indicator, oct_cross_border_participant_indicator, oct_money_transfer_domestic_indicator, oct_money_transfer_cross_border_indicator, oct_money_transfer_fast_funds_domestic_indicator, oct_money_transfer_fast_funds_cross_border_indicator, oct_money_transfer_merchant_country_restricted, oct_non_money_transfer_domestic_indicator, oct_non_money_transfer_cross_border_indicator, oct_non_money_transfer_fast_funds_domestic_indicator, oct_non_money_transfer_fast_funds_cross_border_indicator, oct_online_gambling_domestic_indicator, oct_online_gambling_cross_border_indicator, oct_online_gambling_fast_funds_domestic_indicator, oct_online_gambling_fast_funds_cross_border_indicator].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{self.class.json_map[key]}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{self.class.json_map[key]}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CyberSource.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
